name: Run tests

# Controls when the workflow will run
on:
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run_tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4.4.0
        with:
          java-version: 21
          distribution: temurin

      # Remove MySQL installation
      # No need to install MySQL locally

      - name: Run Unit Tests
        run: |
          mvn test -Dspring.datasource.url=${{ secrets.DB_URL }} \
                   -Dspring.datasource.username=${{ secrets.DB_USERNAME }} \
                   -Dspring.datasource.password=${{ secrets.DB_PASSWORD }} \
                   -Dspring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver \
                   -Dspring.jpa.hibernate.ddl-auto=update \
                   -Dspring.datasource.hikari.connection-timeout=1000 \
                   -Dserver.port=8080
